<?php
/*
 * Added Bullet points in product detail page
 * Get attributes included in "bullet point" group id 
 * Created by AA 26.04.2019
 */
?>

<?php
/* get object of engelsrufer catalog helper */
$helper = $this->helper('Pixelmechanics\Engelsrufer\Helper\Catalog');
/* get current product object */
$_product = $helper->getCurrentProduct();

/**
    added by N.A, on 9.10.19
    trello:https://trello.com/c/FUegOmvv/143-convert-csv-file-and-import-products-from-csv-file-into-relaunch-shop#comment-5d9ca671db243171c540fec8
    - get the Child products of the configurable
*/
    $bullet1 = "";
    $bullet2 = "";
    $bullet3 = "";
    $bullet4 = "";
    $bullet5 = "";


 if($_product->getTypeId() == 'configurable') {

    $usedProducts = $_product->getTypeInstance()->getUsedProducts($_product);
        $childskuwithsize = array();
        $childskuwithgoldsize = array();
            foreach ($usedProducts as $child){
                if($child->getSize()){
                    /*Added the Size key value to the childskuwithsize array*/
                    $childskuwithsize[$child->getSize()] = $child->getSku(); 
                } 

               if($child->getGoldLegierung()){
                    /*add the GoldLegierung key value to the sku by N.A on 10.10.19*/
                     $childskuwithgoldsize[$child->getGoldLegierung()] = $child->getSku();
               } 
                               
            }
             $childSkuKeys = array_keys($childskuwithsize); //get the array key for sorting     
             $childSkuGoldKeys = array_keys($childskuwithgoldsize); //get the gold array key for sorting
            
            /**Make an array of existing values of XS to XL size  by N.A on 9.10.19*/
            $existingSizeValue = array("454","244","245","246","247");
            $existingSizeCM =array("444","445","446","447","455","448","449","450","451");
            /*Existing Size values of CM*/
            $existingGoldLegierungValues = array("593","594","595");
            sort($childSkuKeys); //sort the sku's array key
            sort($existingSizeCM); // sort the Cm varaints values
            sort($childSkuGoldKeys); //sort the sku's array key
            $result = array_intersect($childSkuKeys, $existingSizeValue); //check the sku exist in the array or not
            $resultCM = array_intersect($childSkuKeys, $existingSizeCM); //check the CM values exist or not
            $resultForGold = array_intersect($childSkuGoldKeys, $existingGoldLegierungValues); //check the sku exist in the array or not
           
            /* check if size value intersect then pick the first variant by N.A on 9.10.19*/
            if ((count($result) >= 1) && (count($resultForGold) <=0) && (count($resultCM) <=0)){ // check if the size value is available and gold value is blank
                $childFirstSku = reset($childskuwithsize);     
            } elseif((count($resultForGold) >=1) && (count($result) >=1) && (count($resultCM) <=0)){ 
                // check if the both value (size & gold) is available
                $childFirstSku = reset($childskuwithgoldsize); 
                /*get the first value of GoldLegierung value for the sku by N.A on 10.10.19*/
            } elseif((count($resultForGold) >=1) && (count($result) <=0) && (count($resultCM) <=0)){
                $childFirstSku = reset($childskuwithgoldsize);
            }elseif(count($resultCM) >=1){
                $min_key = min(array_keys($childskuwithsize));
                $min_key_value = $childskuwithsize[$min_key];

                $childFirstSku = $min_key_value; 
            }else{
                $childFirstSku = end($childskuwithsize);   
            }
          
/*load the products based on the first child Sku by N.A on 9.10.19*/
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
    $childproduct = $productRepository->get($childFirstSku);

    $bullet1 = $childproduct->getBulletPoint1();
    $bullet2 = $childproduct->getBulletPoint2();
    $bullet3 = $childproduct->getBulletPoint3();
    $bullet4 = $childproduct->getBulletPoint4();
    $bullet5 = $childproduct->getBulletPoint5();
}
/* get current product attribute ID */
//$productAttributeId = $helper->getAttributeSetId();
/* get attribute group ID of "bullet points */
//$attributeGroupId = $helper->getProductAttributeGroupId('Bullet points');
?>
<?php
/* get current product attributes */
//$productAttributes = $_product->getAttributes();
?>
<ul> 
<?php
//foreach ($productAttributes as $attribute):
    /* check attribute is in group "bullet Id */
   // if ($attribute->isInGroup($productAttributeId, $attributeGroupId)): ?> 
        <?php //if ($attribute->getFrontend()->getValue($_product)): ?>
<!--            <li> <?php //echo $attribute->getFrontend()->getValue($_product); ?> </li>-->
         <?php //endif; ?>
    <?php //endif; ?>
<?php //endforeach; ?>
    <?php // called bullet points manually, updated by AA on 22.08.2019 ?>
    <?php // called bullet points of first varaint, updated by NA on 09.10.2019 ?>
    <li class="bullet-point1 <?php if($_product->getBulletPoint1()): echo 'show-attribute';  else: echo 'hide-attribute'; endif;?>"> <?php if($bullet1): echo $bullet1; else: echo $_product->getBulletPoint1(); endif;?> </li>
    <li class="bullet-point2 <?php if($_product->getBulletPoint2()): echo 'show-attribute';  else: echo 'hide-attribute'; endif;?>"> <?php if($bullet2): echo $bullet2; else: echo $_product->getBulletPoint2(); endif;?> </li>
    <li class="bullet-point3 <?php if($_product->getBulletPoint3()): echo 'show-attribute';  else: echo 'hide-attribute'; endif;?>"> <?php if($bullet3): echo $bullet3; else: echo $_product->getBulletPoint3(); endif;?> </li>
    <li class="bullet-point4 <?php if($_product->getBulletPoint4()): echo 'show-attribute';  else: echo 'hide-attribute'; endif;?>"> <?php if($bullet4): echo $bullet4; else: echo $_product->getBulletPoint4(); endif;?> </li>
    <li class="bullet-point5 <?php if($_product->getBulletPoint5()): echo 'show-attribute';  else: echo 'hide-attribute'; endif;?>"> <?php if($bullet5): echo $bullet5; else: echo $_product->getBulletPoint5(); endif;?> </li>
</ul>