<?php 
/*
* Added By AA on 8.9.2021 
* https://trello.com/c/5BJVIHn6/
* Used file to add the tradetracker script in checkout success page
*/
/* Called helper file "Engelsrufer\Helper\Data.php" */
$helper = $this->helper('Pixelmechanics\Engelsrufer\Helper\Data');
/* Get last order data */
$orderDetails = $helper->getOrderDetails();
?>
<?php /* Added script provided here https://trello.com/c/5BJVIHn6/210-plugin-affiliate-marketing#comment-6130c565dcc93b5c0eaf9caa */ ?>
<script type="text/javascript">
var ttConversionOptions = ttConversionOptions || [];
ttConversionOptions.push({
type: 'sales',
campaignID: '34319', //Static value
productID: '53604',  //Static value
transactionID: <?php echo $orderDetails['transactionId'];?>, //order increment Id
transactionAmount: <?php echo $orderDetails['transactionAmount'];?>, //order grand total
quantity: '1',
email: '',
descrMerchant: '',
descrAffiliate: '',
currency: <?php echo $orderDetails['currency'];?> //order currency
});
</script>

<noscript>
<img src="//ts.tradetracker.net/?cid=34319&amp;pid=53604&amp;tid=<?php echo $orderDetails['transactionId'];?>&amp;tam=<?php echo $orderDetails['transactionAmount'];?>&amp;data=&amp;qty=1&amp;eml=&amp;descrMerchant=&amp;descrAffiliate=&amp;event=sales&amp;currency=EUR" alt="" />
</noscript>

<script type="text/javascript">
// No editing needed below this line.
(function(ttConversionOptions) {
var campaignID = 'campaignID' in ttConversionOptions ? ttConversionOptions.campaignID : ('length' in ttConversionOptions && ttConversionOptions.length ? ttConversionOptions[0].campaignID : null);
var tt = document.createElement('script'); tt.type = 'text/javascript'; tt.async = true; tt.src = '//tm.tradetracker.net/conversion?s=' + encodeURIComponent(campaignID) + '&t=m';
var s = document.getElementsByTagName('script'); s = s[s.length - 1]; s.parentNode.insertBefore(tt, s);
})(ttConversionOptions);
</script>