<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Sidebar $block */
/*
 * Ovrride by AA on 18.05.2019
 * Wishlist collection
 */
?>
<?php
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
?>
<?php if ($wishlistHelper->isAllow()) : ?>
    <div class="block block-wishlist" data-bind="scope: 'wishlist'">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?= __('My Wishlist'); ?></strong>

        </div>
        <div class="block-content">
            <!-- ko if: wishlist().counter -->
                <ol class="product-items no-display" id="wishlist-sidebar" data-bind="foreach: wishlist().items, css: {'no-display': null}">
                    <li class="product-item">
                        <div class="product-item-info">
                            <a class="product-item-photo" data-bind="attr: { href: product_url, title: product_name }">
                                <!-- ko template: {name: $data.image.template, data: $data.image} --><!-- /ko -->
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a data-bind="attr: { href: product_url }" class="product-item-link">
                                        <span data-bind="html: product_name"></span>
                                    </a>
                                </strong>
                                <div class="product_inner-wrapper">
                                    <div data-bind="html: product_price"></div>
                                    <?php echo $block->getChildHtml('tax-info');?>
                                <?php // added variant info for configurable products, Added by AA on 30.05.2019 ?>
                                    <!-- ko if: product_variant -->
                                        <div class="number-variant"><span data-bind="html: product_variant"></span>
                                            <?php echo __("Variants");?>
                                        </div>
                                     <!-- /ko -->
                                </div>
                          <?php // "Add to cart" button for simple and "go to product" for configurable product, updated by NA on 29.06.2019 ?>
                                <div class="product-item-actions">
                                    <!-- ko if: product_is_saleable_and_visible -->
                                    <div class="actions-primary">
                                        <!-- ko if: product_has_required_options -->
                                        <a href="#" data-bind="attr: {'data-post': add_to_cart_params}" class="action tocart primary">
                                            <!-- ko ifnot: product_type=='configurable' -->
                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            <!-- /ko -->
                                            <!-- ko if: product_type=='configurable' -->
                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            <!-- /ko -->
                                        </a>
                                        <!-- /ko -->
                                        <!-- ko ifnot: product_has_required_options -->
                                            <button type="button" class="action tocart primary" data-bind="attr: {'data-post': add_to_cart_params}">
                                                <!-- ko ifnot: product_type=='configurable' -->
                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            <!-- /ko -->
                                            <!-- ko if: product_type=='configurable' -->
                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            <!-- /ko -->
                                            </button>
                                        <!-- /ko -->
                                    </div>
                                    <!-- /ko -->
                                </div>
                                <?php //endif;?>
                            </div>
                        </div>
                    </li>
                </ol>
                <div class="actions-toolbar no-display" data-bind="css: {'no-display': null}">
                    <div class="primary">
                        <a class="action details"
                           href="<?= $block->escapeUrl($this->helper('Magento\Wishlist\Helper\Data')->getListUrl()) ?>"
                           title="<?= $block->escapeHtmlAttr(__('Go to Wish List')) ?>"><span><?= $block->escapeHtml(__('Go to Wish List')) ?></span></a>
                    </div>
                </div>
            <!-- /ko -->
            <!-- ko ifnot: wishlist().counter -->
                <div class="empty"><?= $block->escapeHtml(__('You have no items in your wish list.')) ?></div>
            <!-- /ko -->
        </div>
    </div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }
</script>
<?php endif ?>
