<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Mostviewed
 */
?>
<?php
    /**
     * @var \Amasty\Mostviewed\Block\Product\Popup $block
     * @codingStandardsIgnoreFile
     */
?>
<div class="amrelated-popup-container" data-amrelated-js="bundle-popup">
    <div class="amrelated-bundle-popup">
        <span title="<?= $block->escapeHtml(__('Close')) ?>" class="close" data-amrelated-js="close-popup"></span>
        <div class="amrelated-products-wrapper" data-amrelated-js="products-wrapper">
            <div class="amrelated-notice">
                <p><?= $block->escapeHtml(__('Some products of the bundle pack were not added to cart.')); ?></p>
                <p><?= $block->escapeHtml(__('Please choose the options to add them.')); ?></p>
            </div>
            <?php foreach ($block->getProducts() as $productId => $item) : ?>
                <div class="amrelated-product-container" id="amrelated-product-container-<?= /* @noEscape */ $productId;?>">
                    <div class="amrelated-product-message">
                        <?= /* @noEscape */ $item['message'] ?>
                    </div>
                    <div class="amrelated-product-content">
                        <?= /* @noEscape */ $item['html'] ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="amrelated-popup-tocart-wrapper">
            <button class="action primary" type="button"
                    data-amrelated-js="add-to-cart-popup"
                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>">
                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
            </button>
        </div>
        <script type="text/x-magento-init">
            {
                "[data-amrelated-js='add-to-cart-popup']": {
                    "Amasty_Mostviewed/js/ampackcart_popup": <?= /* @noEscape */ $block->getJsonConfig();?>
                }
            }
        </script>
    </div>
</div>
