<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Cookie\Block\Html\Notices $block */
/* Updated By AA on 26.06.2019, added cms block for content and add more and less buton */
?>
<?php if ($this->helper(\Magento\Cookie\Helper\Cookie::class)->isCookieRestrictionModeEnabled()): 
$helperData = $this->helper('Pixelmechanics\Engelsrufer\Helper\Data');?>
    <div role="alertdialog"
         tabindex="-1"
         class="message global cookie"
         id="notice-cookie-block"
         style="display: none;">
        <div role="document" class="content" tabindex="0">
            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('cookie_content')->toHtml();?>
            <div class="actions">
                <!-- <button id="btn-more-info" class="action allow primary">
                    <span><?= $block->escapeHtml(__('More Information')) ?></span>
                </button>
                <button id="btn-less-info" class="action allow primary" style="display: none">
                    <span><?= $block->escapeHtml(__('Less Information')) ?></span>
                </button> -->
                <?php
                /*
                 * More info url on the basis of store, translated in translate csv file
                 * For En store URL is "data-protection" and for DE store URL is "datenschutz"
                 * Removed trailing slash by adding '_direct'
                 * Updated By AA on 14.11.2019
                 * https://trello.com/c/W6c5ckeI/295-bug-seobility-and-deeptrawl-registrate-too-many-sites-on-engelsrufer#comment-5dcceef37dfbd64375760efb
                 */
                ?>
                <?php $moreInfoUrl = __('data-protection'); ?>
                <a class="action allow primary" href="<?php echo $this->getUrl('', array('_direct'=> $moreInfoUrl));?>"><?= $block->escapeHtml(__('More Information')) ?></a>
                <button id="btn-cookie-allow" class="action allow primary">
                    <span><?= $block->escapeHtml(__('I accept')) ?></span>
                </button>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "#notice-cookie-block": {
                "cookieNotices": {
                    "cookieAllowButtonSelector": "#btn-cookie-allow",
                    "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                    "cookieValue": <?= /* @noEscape */ $this->helper(\Magento\Cookie\Helper\Cookie::class)->getAcceptedSaveCookiesWebsiteIds() ?>,
                    "cookieLifetime": <?= /* @noEscape */ $this->helper(\Magento\Cookie\Helper\Cookie::class)->getCookieRestrictionLifetime() ?>,
                    "noCookiesUrl": "<?= $block->escapeJs($block->escapeUrl($block->getUrl('cookie/index/noCookies'))) ?>"
                }
            }
        }
    </script>
<?php endif; ?>
