<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   Lof
 * @package    Lof_BasePrice
 * @subpackage view
 * @author     Landofcoder <landofcoder@gmail.com>
 * @copyright  Copyright (c) 2020 Landofcoder (https://landofcoder.com)
 * @link       https://landofcoder.com
 */

/**
 * @var $block \Lof\BasePrice\Block\AfterPrice
 */
?>
<?php if ($block->isEnabled()): ?>
    <div class="baseprice">
        <?php echo $block->getBasePrice() ?>
    </div>
<?php endif; ?>
