<?php
/**
 * @copyright Copyright (c) 2016 www.tigren.com
 */
/*
 * Design error popup after add to cart
 * Updated by AA on 09.08.2019
 */
?>
<?php $_product = $block->getProduct(); ?>
<div class="mb-login-popup-title center">
    <strong><?php echo __('Error'); ?></strong>
</div>
<div class="mb-ajaxsuite-popup-border ajaxcart-success-box">
    <div class="error-content modal-content-col">
        <p class="error-message"></p>
        <div class="product-image">
            <?php echo $block->getChildHtml('product_image'); ?>
        </div>
         <div class="product-info">
             <div class="product-name"><?php echo $_product->getName() ?></div>
              <?php echo $block->getChildHtml('tax-info'); ?>
              <?php echo $block->getChildHtml('product_option'); ?>
        </div>
    </div>
    <div class="link">
        <?php echo $block->getChildHtml('product_links'); ?>
    </div>
    <div class="ajaxcart-buttons ajaxsuite-buttons">
        <button type="button" id="ajaxcart_cancel" class="action primary mb-ajaxsuite-close"
                title="<?php echo __('Continue shopping') ?>">
            <span><?php echo __('Continue shopping') ?></span>
            <?php
            if ($popupTTL = $this->helper('Tigren\Ajaxsuite\Helper\Data')->getTTLAjaxSuite()) {
                ?>
                (<span class="ajaxsuite-autoclose-countdown"><?php echo $popupTTL ?></span>)
                <?php
            }
            ?>
        </button>
    </div>
</div>